export {default as Home} from './Home/Home';
export {default as GroupContact} from './GroupContact/GroupContact';
export {default as Team} from './Team/Team';
export {default as Setting} from './Setting/Setting';
export {default as ScanScreen} from './Scan/ScanScreen';
export {default as ForgotPassword} from './ForgotPassword/ForgotPassword'
export {default as ChangePassword} from './ChangePassword/ChangePassword'
export {default as SignIn} from './SignIn/SignIn'
export {default as Splash} from './Splash/Splash'
export {default as ViewContact} from './ViewContact/ViewContact'
export {default as AddContact} from './AddContact/AddContact'
export {default as UpdateContact} from './UpdateContact/UpdateContact'