export {default as Home} from './Home/Home';
export {default as GroupContact} from './GroupContact/GroupContact';
export {default as Team} from './Team/Team';
export {default as Setting} from './Setting/Setting';
export {default as ScanScreen} from './Scan/ScanScreen';
export {default as ForgotPassword} from './ForgotPassword/ForgotPassword'
export {default as ChangePassword} from './ChangePassword/ChangePassword'
export {default as SignIn} from './SignIn/SignIn'
export {default as Splash} from './Splash/Splash'
export {default as ViewContact} from './ViewContact/ViewContact'
export {default as AddContact} from './AddContact/AddContact'
export {default as UpdateContact} from './UpdateContact/UpdateContact'
export {default as SearchContact} from './SearchContact/SearchContact'
export {default as GroupContactDetail} from './GroupContactDetail/GroupContactDetail'
export {default as AddContactToGroup} from './AddContactToGroup/AddContactToGroup'
export {default as ResetPasswordCode} from './ResetPasswordCode/ResetPasswordCode'
export {default as AddContactToManyGroup} from './AddContactToManyGroup/AddContactToManyGroup'
export {default as DeleteContactFromGroup} from './DeleteContactFromGroup/DeleteContactFromGroup'
export {default as ResetPassword} from './ResetPassword/ResetPassword'
//export {default as ViewContactMember} from './ViewContactMember/ViewContactMember'
