//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int id { get; set; }
        public int requester { get; set; }
        public int receiver { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> contact_id_duplicate { get; set; }
        public string code { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual contact contact1 { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
